### ISSUE TITLE
Several calls to undefined functions

### ISSUE THREAD

**Issue by cobbjb** [Cacti/plugin_mikrotik#1]
PHP Fatal error:  Call to undefined function top_header() in /usr/local/share/cacti/plugins/mikrotik/mikrotik_users.php on line 46, referer: http://192.168..x.x/cacti/graph_templates.php

PHP Fatal error:  Call to undefined function general_header() in /usr/local/share/cacti/plugins/mikrotik/mikrotik.php on line 39, referer: http://192.168.x.x/cacti/settings.php

PHP Fatal error:  Call to undefined function top_header() in /usr/local/share/cacti/plugins/mikrotik/mikrotik_users.php on line 46

**Comment by cigamit** [comment]
What version of Cacti?  This plugin currently will only work with the latest git of Cacti 1.0.

**Comment by cobbjb** [comment]
I'm running 0.8.8b.  Is there an older version of this plugin that works with this version?  Cacti 1.0 doesn't appear to be making the cut into even Debian testing's repo.

**Comment by cigamit** [comment]
Should be one at
http://docs.cacti.net/plugin:mikrotik

We always recommend to install Cacti direct from source instead of a package.
