### ISSUE TITLE
Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.11.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339

### ISSUE THREAD

**Issue by semakka1975** [Cacti/plugin_mikrotik#15]
got tome errors while adding a MKTK 493AH with 3 MIniPCI radio cards on 5GHz - AP mode all.
Can PM the  Supout.rif for debug if needed.
ROS 6.39.2 FW 3.24.
MKTK plugin on cacti 1.1.9 with MikroTik_Device.xml.gz imported correctly via CLI using 'import_package.php'  
just to mention, I didn't even added graphs to this host but seems to be already looking for radio related OIDs, what if the MKTK hasn't got wireless devicess?. 
Errors are: 

`2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.11.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.10.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.9.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.8.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.7.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.6.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.5.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.3.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.2.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339
2017/06/17 16:16:08 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 798 collect_wireless_aps)(/plugins/mikrotik/poller_mikrotik.php: 1353 collectHostIndexedOid)(/plugins/mikrotik/poller_mikrotik.php: 1025 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4359 cacti_debug_backtrace)
2017/06/17 16:16:08 - ERROR PHP WARNING in Plugin 'mikrotik': snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.4.1.14988.1.1.1.3.1.4.12 in file: /var/www/html/cacti/plugins/mikrotik/snmp.php on line: 339`

cheers
S

**Comment by cigamit** [comment]
Latest MikroTik uses cacti snmp library.  Should be better now.
