### ISSUE TITLE
Interfaces showing as Wireless Stations

### ISSUE THREAD

**Issue by mattymrm** [Cacti/plugin_mikrotik#16]
Added a Mikrotik RB2011UiAS-RM and its returning no rows for anything under Associated Data Queries apart from Wireless Stations which are the actual interfaces of the Mikrotik and not Wireless Stations. All the templates imported ok and plugin enabled etc. Using Cacti 1.1.7.

**Comment by cigamit** [comment]
This is resolved in 2.1.  You should re-import the package after you upgrade.
