### ISSUE TITLE
Doesnt work for version 6.39.2

### ISSUE THREAD

**Issue by MDE186** [Cacti/plugin_mikrotik#17]
Cacti v1.1.13
using cmd.php poller
SNMP timeout set to 5000ms
Version 
 - https://github.com/Cacti/plugin_mikrotik/commit/ac9c106bb8c7b973e25dbbe7f3898071ffd8ee12

Through terminal ssh - xxx:~$ snmpwalk -v 2c -c public 192.168.1.1 .1.3.6.1.4.1.14988.1.1.2.1.1.2
iso.3.6.1.4.1.14988.1.1.2.1.1.2 = No Such Object available on this agent at this OID

![image](https://user-images.githubusercontent.com/8092312/28518002-b455417c-7066-11e7-9bdc-af188ed8e8c7.png)

Maybe the OIDs in the script are outdated...sorry if they are not as I quickly ran through this as a test.

**Comment by MDE186** [comment]
Something new as well not sure if its related....
![image](https://user-images.githubusercontent.com/8092312/28523193-8468fd90-707b-11e7-8848-fd21c5ae9d0e.png)

**Comment by cigamit** [comment]
SQL Error fixed in 1.1.16
