### ISSUE TITLE
Cant access "Discovered Devices"

### ISSUE THREAD

**Issue by MDE186** [Cacti/plugin_mikrotik#18]
Once the plugin has been installed and activated the sub directory of Automation "Discovered Devices" becomes in accessible...

If the mikrotik plugin is uninstalled the "Discovered Devices" is accessible again...

**Comment by cigamit** [comment]
Please update to 1.1.16, and verify freetype is installed.

**Comment by MDE186** [comment]
I've upgraded to 1.1.16 enabled the Mikrotik plugin again but still does not allow me to access the "Discovered Devices" 

![image](https://user-images.githubusercontent.com/8092312/29017071-8d2e2b1e-7b55-11e7-8d1a-e42b90b79d97.png)

![image](https://user-images.githubusercontent.com/8092312/29017110-b7d8e714-7b55-11e7-9caa-4d1c978f453f.png)

**Comment by MDE186** [comment]
Have updated the poller_graphs.php with the latest commits. Unfortunately it still does no work.

Still getting the same error as above. Thanks for the efforts.

**Comment by cigamit** [comment]
You need to change setup.php and poller_graphs.php.  You only updated the one.

**Comment by MDE186** [comment]
All working. sorry about that :)
