### ISSUE TITLE
Has issues with newer Mikrotik RouterOS release 6.37.1 (

### ISSUE THREAD

**Issue by bloodyle** [Cacti/plugin_mikrotik#2]
Since RouterOS upgrade to 6.37.1 the Mikrotik OID's seem not working properly anymore.
While everything is still operating and OID's are getting Data from the router, the Data seems not to make sense anymore.
See the difference in this Image: [(https://www.dropbox.com/s/innz6hgnmt11gig/issue.png?dl=0)]
The Plugin graphed properly the Quota for that user till the 25th when we upgraded the Mikrotik CCR1036 from RoS 6.34 to 6.37.1. This behavior seems for all OID's similarly wrong now.

**Comment by cigamit** [comment]
Can you test with 6.38.5 and let me know if it's working again?

**Comment by cigamit** [comment]
No feedback.

**Comment by bloodyle** [comment]
Yes, fixed since 6.38.5 and still OK on 6.40.3
