### ISSUE TITLE
router_api_class.php Poller_log Error - Line 114

### ISSUE THREAD

**Issue by MDE186** [Cacti/plugin_mikrotik#21]
![image](https://user-images.githubusercontent.com/8092312/29210537-59e01000-7e94-11e7-94f3-c2bfe643ac89.png)

Not related to the above:

-How does one set the username and password for the api to login to the devices? The mikrotik log is showing hundreds of failed attempts for login?
-Im not sure if the poller is supposed to collect the username information but I cannot create a user under the tab "MikroTik Users" under the console. As in there is no "+" or "add' button.

**Comment by cigamit** [comment]
Get the latest development snapshop and this warning will go away, and then you setup the user and password when you edit the Device.

**Comment by cigamit** [comment]
You can setup automation if you have a lot of Tiks.  Start with the Device Template in Automation Templates, then setup a Network.  Otherwise, Cacti assumes that you manually added the Tiks to Cacti.
