### ISSUE TITLE
New Cacti install, all Mikrotik health graphs are empty.

### ISSUE THREAD

**Issue by keeth** [Cacti/plugin_mikrotik#22]
Hi! I'm new to Mikrotik and Cacti.  I've got Cacti 1.1.23, RouterOS 6.40.3, and using the develop branch of this plugin.

I've added my router device in Cacti and I am seeing graphs for interface traffic.. however my Mikrotik health graphs are empty.

snmpwalk is giving correct data

Logs follow.. any things I could try to debug this further?

Thanks!

    2017/09/16 02:20:01 - POLLER: Poller[1] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '300.39', Max Runtime '298', Poller Runs: '1'
    2017/09/16 02:20:01 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
    2017/09/16 02:20:01 - PHPSVR PHP Script Server has Started - Parent is cmd
    2017/09/16 02:20:01 - POLLER: Poller[1] PHP Script Server Started Properly
    2017/09/16 02:20:02 - PING Device[1] SNMP: Device responded to SNMP
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] STATUS: Device '192.168.1.1' is UP.
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE: Processing 6 items in the auto reindex cache for '192.168.1.1'.
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE DQ[1] OID: .1.3.6.1.2.1.1.3.0, output: 47700
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE DQ[2] OID: .1.3.6.1.2.1.1.3.0, output: 47700
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE DQ[3] OID: .1.3.6.1.2.1.1.3.0, output: 47700
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE DQ[4] OID: .1.3.6.1.2.1.1.3.0, output: 47700
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE DQ[5] OID: .1.3.6.1.2.1.1.3.0, output: 47700
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] RECACHE DQ[6] OID: .1.3.6.1.2.1.1.3.0, output: 47700
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[1] SERVER: /opt/cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_cpu.php ss_mikrotik_cpu '1', output: cpu: max:
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[2] SERVER: /opt/cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_health.php ss_mikrotik_health '1' 'HlPower', output: U
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[3] SERVER: /opt/cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_health.php ss_mikrotik_health '1' 'HlTemperature', output: U
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[4] SERVER: /opt/cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_health.php ss_mikrotik_health '1' 'HlVoltage', output: U
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[5] SNMP: v2: 192.168.1.1, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.11, output: 1016044
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[5] SNMP: v2: 192.168.1.1, dsname: traffic_out, oid: .1.3.6.1.2.1.2.2.1.16.11, output: 4195498
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[6] SNMP: v2: 192.168.1.1, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.14, output: 4106462
    2017/09/16 02:20:02 - POLLER: Poller[1] Device[1] DS[6] SNMP: v2: 192.168.1.1, dsname: traffic_out, oid: .1.3.6.1.2.1.2.2.1.16.14, output: 940542
    2017/09/16 02:20:02 - POLLER: Poller[1] Time: 1.4080 s, Poller: , Theads: N/A, Devices: 1
    2017/09/16 02:20:03 - POLLER: Poller[1] Parsed MULTI output field 'cpu:' [map cpu->cpu]
    2017/09/16 02:20:03 - POLLER: Poller[1] Parsed MULTI output field 'max:' [map max->max]
    2017/09/16 02:20:03 - SYSTEM STATS: Time:2.2209 Method:cmd.php Processes:1 Threads:N/A Hosts:1 HostsPerProcess:1 DataSources:8 RRDsProcessed:6

snmpwalk:

    root@ip-172-31-47-213:/opt/cacti# snmpwalk -c public -v2c 192.168.1.1:8161 .1.3.6.1.4.1.14988.1.1.3
    iso.3.6.1.4.1.14988.1.1.3.8.0 = INTEGER: 119
    iso.3.6.1.4.1.14988.1.1.3.9.0 = STRING: "main"
    iso.3.6.1.4.1.14988.1.1.3.10.0 = INTEGER: 240
    iso.3.6.1.4.1.14988.1.1.3.11.0 = INTEGER: 300
    iso.3.6.1.4.1.14988.1.1.3.12.0 = INTEGER: 109
    iso.3.6.1.4.1.14988.1.1.3.13.0 = INTEGER: 924
    iso.3.6.1.4.1.14988.1.1.3.14.0 = INTEGER: 1066
    iso.3.6.1.4.1.14988.1.1.3.17.0 = INTEGER: 6935

<img width="1145" alt="screen shot 2017-09-15 at 7 27 19 pm" src="https://user-images.githubusercontent.com/239868/30508436-ffe22ea2-9a4b-11e7-8e16-b79c6e27a37f.png">

**Comment by cigamit** [comment]
Right now, if the MikroTik does not support the OID, you won't get data.  This is a similar issue to what was reported recently by another user.  It's a core cacti feature that I had planned for the 1.2 release.  You can look at the short term resolution in the post here: https://github.com/Cacti/plugin_mikrotik/issues/24

**Comment by netniV** [comment]
The duplicate was closed, does this mean this is also resolved?
