### ISSUE TITLE
The health values are showed without dot

### ISSUE THREAD

**Issue by jlazkano** [Cacti/plugin_mikrotik#23]
Hello,

The health values of the Mikrotik routers are showed without the decimal dot. I try it in a RB3011 and RB450G devices.

Here is a example:

<a href="http://tinypic.com?ref=dxbe3a" target="_blank"><img src="http://i66.tinypic.com/dxbe3a.png" border="0"></a>

And here is what it show:

<a href="http://tinypic.com?ref=nnur87" target="_blank"><img src="http://i67.tinypic.com/nnur87.png" border="0"></a>

<a href="http://tinypic.com?ref=331g7yd" target="_blank"><img src="http://i65.tinypic.com/331g7yd.png" border="0"></a>

Kind regards.

**Comment by cigamit** [comment]
Thanks for the update.  I'll have to look into this as soon as I get time to spend on this plugin again.

**Comment by cigamit** [comment]
Should be resolved now.
