### ISSUE TITLE
Mikrotik : Simple queue Graph

### ISSUE THREAD

**Issue by sachinn19** [Cacti/plugin_mikrotik#25]
Hello Guys,

Recently i use cacti for graph my mikrotik network, by doing this graphs are generated only for interface statistics, but not able to generate graphs for simple queue.

Pl. suggest!!

Regards,
Sachin

**Comment by cigamit** [comment]
Do you have any errors in your cacti.log file?  Looking for SQL errors or snmpwalk errors.

**Comment by sachinn19** [comment]
Dear Sir,
I am new to Cacti, pls. tell me how to check logs.I think for Simple queue i need to add some plugins, kindly suggest the same.


Regards,Sachin

**Comment by sachinn19** [comment]
Dear Sir,

I am new to Cacti, pls. tell me how to check logs for simple queue.
I think for Simple queue i need to add some plugins, kindly suggest the same.



Regards,
Sachin

**Comment by cigamit** [comment]
This is not really the place for a user to learn how to install a plugin.  It's more for issues once you have come up to speed.  I suggest you open a request on the forums as that is how we officially provide support.  This location is only for bug reports.  As such, and not meaning to be mean, I will close this ticket.  You can get to the forums at http://forums.cacti.net.

As a starter, you need to follow the instructions in the README.md file at this GitHub.  Part of that is importing the MikroTik Device template.  Then, you have to add your MikroTik to Cacti, using snmp, and the administrators id and password.  Then, by default, the simple queues should be collected and appear automatically in the interface, unless you have disabled their collection.  To Enable/Disable collection, you do that from Console > Settings > MikroTik.

If you have any other questions, this is not the right place to ask them.

**Comment by sachinn19** [comment]
ok, i will put my query to cacti forum, but as you mention that cacti will generate simple queue graph by default.. it is not done.. while i am able to generate graph at mikrotik end, not in cacti.

**Comment by sachinn19** [comment]
ok, i will put my query to cacti forum, but as you mention that cacti will generate simple queue graph by default.. it is not done.. while i am able to generate graph at mikrotik end, not in cacti.
