### ISSUE TITLE
Graphs were not created, everytime needs to refresh verbose query then its created

### ISSUE THREAD

**Issue by sachinn19** [Cacti/plugin_mikrotik#26]
Hello All,

i am using cacti version 0.8.8f, i am facing very odd issue, mikrotik interface graphs were created but pppoe users graphs are not created automatically, every time need to refresh the verbose query. after refreshing verbose query and save, graphs are creating. Please let me help why i supposed to refresh every time.

**Comment by cigamit** [comment]
This version of the plugin only runs on Cacti 1.X, there will be no fixes forthcoming for old versions of the plugin that run on older versions of Cacti.
