### ISSUE TITLE
Not sure how to use "import_package.php" to import MikroTik package

### ISSUE THREAD

**Issue by nhenpanha** [Cacti/plugin_mikrotik#29]
Hi team,

could you tell me detail how to "import_package.php" to use Mikrotik plugin?

**Comment by netniV** [comment]
If you are talking about Import Package under the Console -> Import/Export of Cacti, that isn't for plugins.  That is purely for templates/data queries.

**Comment by nhenpanha** [comment]
Here is my problem:

on the installation guide, I am not clear about how to use import_package.php CLI.

" With this version of mikrotik, we are also including a Device Template Cacti Package that includes everything you need to create all the included Cacti Graphs for this device type. To import that package, you must use the Cacti '### import_package.php' CLI script. The MikroTik package is included in the 'templates' sub-directory of the MikroTik plugin."

**Comment by netniV** [comment]
Oh, OK.  Sorry, forgot about that.  To do that you must use the following:

```bash
php -q <cactidir>/cli/import_package.php --filename=<template package>
```

Replace <cactdir> with the path to the cacti root folder and <template_package> with a full path to the template to be imported.

**Comment by kaamil1984** [comment]
> Oh, OK. Sorry, forgot about that. To do that you must use the following:
> 
> ```shell
> php -q <cactidir>/cli/import_package.php --filename=<template package>
> ```
> 
> Replace with the path to the cacti root folder and <template_package> with a full path to the template to be imported.

I think that information should be in README. CLI term may have more than 1 meaning in Cacti.
