### ISSUE TITLE
After delete some graph, it show error messages

### ISSUE THREAD

**Issue by nhenpanha** [Cacti/plugin_mikrotik#30]
Please kindly checking my problem below:
![image](https://user-images.githubusercontent.com/11862935/42406303-2c54c88a-81cf-11e8-90b0-6b318b0826b2.png)
![image](https://user-images.githubusercontent.com/11862935/42406304-4093be8c-81cf-11e8-9cbc-26998c9d0813.png)

**Comment by nhenpanha** [comment]
![image](https://user-images.githubusercontent.com/11862935/42406515-79263cf8-81d3-11e8-9907-8d2222a9fb2e.png)

**Comment by netniV** [comment]
The sizeof error is probably due to you using php 7.2, am I right?

**Comment by cigamit** [comment]
This is a Cacti issue that has been solved for quite some time.  Closing.
