### ISSUE TITLE
No Uptime and a non mikrotik device detected

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/plugin_mikrotik#32]
Hi everyone, using the latest realease of the plugin (Stable) and cacti 1.2.1 i don't get the users information (simply says 0 users) and 1 non mikrotik device get detected, there are no error logs and the rest of the sections of the pluging work just fine.

this is the log entry related to the plugin:

22/02/2019 11:09:25 - SYSTEM MIKROTIK STATS: Time:37.1300 Processes:10 Hosts:3 Interfaces:36 Queues:2 Users:0 Trees:13 Waps:2 Wreg:5

and a capture:

![mtik](https://user-images.githubusercontent.com/37849594/53251632-7c005600-3693-11e9-9a73-15507fd9a90a.png)

**Comment by DoubleBeast** [comment]
i just notice in the image that the uptime doesn't show and in the general device management page is shown correctly

**Comment by netniV** [comment]
Devices that are not showing the number of users, try walking the SNMP for oid `.1.3.6.1.4.1.14988.1.1.5.1.1` which covers all the user-based data that is collected.  The chances are, your device isn't actually giving out any user information so it can't be tracked.

**Comment by DoubleBeast** [comment]
> 
> 
> Devices that are not showing the number of users, try walking the SNMP for oid `.1.3.6.1.4.1.14988.1.1.5.1.1` which covers all the user-based data that is collected. The chances are, your device isn't actually giving out any user information so it can't be tracked.

you are rigth mark, that oid is for hotspot user (i don`t use hotspot so result zero in my case) and i thougt that the users refered in the plugin were administrative user, my bad in that case.

**Comment by cigamit** [comment]
Yea, just confirmed this.  Giving Mikrotik a dusting off.  Will have a new release out shortly.

**Comment by cigamit** [comment]
Okay, uptime is reporting correctly again.
