### ISSUE TITLE
Mikrotik graph error

### ISSUE THREAD

**Issue by Rameshkc998** [Cacti/plugin_mikrotik#33]
I just fresh installed Latest Cacti Version 1.2.4 in centos 7 with latest Mikrotik Plugin v1.x installed from github. But I cannot create graph for my Mikrotik Device, because the system said Data Query Returned 0 like this images
![image](https://user-images.githubusercontent.com/47779207/58161006-31e13d80-7c9f-11e9-96ce-ea4843666384.png)

**Comment by Rameshkc998** [comment]
When i open the graph in debuugging mode i get
![image](https://user-images.githubusercontent.com/47779207/58161158-78cf3300-7c9f-11e9-8710-37383b1cf5f9.png)

**Comment by Rameshkc998** [comment]
Only few graphs are showing currently
![image](https://user-images.githubusercontent.com/47779207/58161232-9a301f00-7c9f-11e9-99b5-d751997fdcc7.png)

**Comment by cigamit** [comment]
Have you set the data collection frequencies and enabled data collection?  Settings > MikroTik.

**Comment by ptaabodi** [comment]
> Have you set the data collection frequencies and enabled data collection? Settings > MikroTik.

Hi
I have the same Problem with same error message and I set data collection frequencies and I enabled data collection in Settings > MikroTik, but i still have problem and no interface and queue information displayed.
do you have any ideas?
tanx

**Comment by huangchao-shanghai** [comment]
![image](https://user-images.githubusercontent.com/3233883/61713990-61d6bb00-ad8c-11e9-8c4f-9476019c2db2.png)

/lib/data_query.php
sizeof($script_num_index_array) return 0
looks like a bug

**Comment by netniV** [comment]
That would mean nothing was returned by the MySQL query. You could try `var_dump`'ing the `$script_num_index_array`

**Comment by huangchao-shanghai** [comment]
[var_dump($script_num_index_array)](url) return empty

but foreach working normally.
```
foreach ($script_num_index_array as $element) {
	query_debug_timer_offset('data_query', __('Found number of indexes: %s' , $element));
}
```

comment out ` //return false;  `can be solved temporarily.
![image](https://user-images.githubusercontent.com/3233883/61783116-cef45a00-ae39-11e9-9962-b019205b00bf.png)

**Comment by cigamit** [comment]
What data query is this for.  I don't see any microtik device templates that use arg_num_indexes, which is what you have commented out.

**Comment by cigamit** [comment]
My guess is that if you update Cacti to 1.2.5, this issue will be resolved on it's own.

**Comment by huangchao-shanghai** [comment]
Data query
MikroTik - Interfaces
MikroTik - Queues
![image](https://user-images.githubusercontent.com/3233883/61883927-dc8b0c00-af2d-11e9-9168-520673538e3c.png)

**Comment by huangchao-shanghai** [comment]
commented out:
`return false;`
![image](https://user-images.githubusercontent.com/3233883/61884745-58d21f00-af2f-11e9-803c-eba31e193198.png)

**Comment by bvr373** [comment]
same problem with cacti 1.2.5, php73, mariadb10.4, rrdtool1.8+

any update?

**Comment by cigamit** [comment]
This issue is solved here.  It will be a part of 1.2.7.

https://github.com/Cacti/cacti/issues/2974

**Comment by bvr373** [comment]
This Data Query returned 0 rows, perhaps there was a problem executing this Data Query.You can run this Data Query in debug mode From there you can get more information.

Status:   | Success [0 Items, 0 Rows]



![Capture](https://user-images.githubusercontent.com/28857084/66288312-8ea76280-e8e5-11e9-8779-9f138b02f60b.JPG)
![Capture2](https://user-images.githubusercontent.com/28857084/66288315-90712600-e8e5-11e9-89a6-d9f59e23c0cf.JPG)
