### ISSUE TITLE
Graphing issues on fresh install Cacti 1.2.3 Mikrotik plugin 2.3

### ISSUE THREAD

**Issue by jorgecg89** [Cacti/plugin_mikrotik#34]
Hi.

I have a fresh installatio, but after traying to graph of my Mikrotik got those errors on the logs, and only routing table and arp entries are working.

`
CMDPHP SQL Backtrace: (/plugins/mikrotik/poller_mikrotik.php[135]:process_hosts(), /plugins/mikrotik/poller_mikrotik.php[635]:db_execute(), /lib/database.php[187]:db_execute_prepared())
2019/06/20 17:45:58 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.plugin_mikrotik_storage' doesn't exist
2019/06/20 17:45:58 - CMDPHP SQL Backtrace: (/plugins/mikrotik/poller_mikrotik.php[135]:process_hosts(), /plugins/mikrotik/poller_mikrotik.php[608]:db_execute(), /lib/database.php[187]:db_execute_prepared())
2019/06/20 17:45:05 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[2.O-RB1100AHx2] Thread[1] DS[2.O-RB1100AHx2 - Uptime] Graphs[2.O-RB1100AHx2 - Uptime]
`

Saw on cacti forums someone else having the same issue.

**Comment by cigamit** [comment]
Please ensure you have the following set:

``` console
innodb_file_per_table = ON
innodb_file_format  = Barracuda
innodb_large_prefix = 1
```

After you have verified that, restart MariaDB/MySQL and then run the following CLI command:

``` console
cd /var/www/html/cacti/cli
php -q repair_database.php --dynamic
```

Then, uninstall and reinstall the plugin.

**Comment by Paulf007** [comment]
My apologies but where do I set these settings. Sorry for the Noob question
