### ISSUE TITLE
Login Failure for RouterOS Login method post-v6.43: 

### ISSUE THREAD

**Issue by sciamachy** [Cacti/plugin_mikrotik#35]
The Login Method has changed for post-v6.43.  See https://wiki.mikrotik.com/wiki/Manual:API.

The following modification to the connect() function in routeros_api.class.php will resolve this (though break backwards compatibility). May make sense to either try both, or have the user config the version.

$this->write('/login');
$this->write('=name=' . $login, false);
$this->write('=password=' . $password, false);
$RESPONSE = $this->read(false);
if (isset($RESPONSE[0]) && $RESPONSE[0] == '!done') {
     $this->connected = true;
     break;
}

**Comment by bvr373** [comment]
![s](https://user-images.githubusercontent.com/28857084/94405398-121b2d00-01a3-11eb-8842-11e9e33dfc6d.jpg)
Hello Dear cigamit,

I have same problem, User logged in/logged out by API

**Comment by TheWitness** [comment]
We updated the API some time ago to address this.
