### ISSUE TITLE
Mikrotik Plugin -- simple queue issue

### ISSUE THREAD

**Issue by WAMPerera** [Cacti/plugin_mikrotik#36]
Hi team,

I have installed centos-7 cacti version 1.2.6 and mikrotik plugin 2.2 installed,. 

cacti couldn't capture any statistic about mikrotik routers.  where could be the issue

after I change data input method --> to script/data I get this message on my logs

2019/10/08 11:41:44 - CMDPHP PHP ERROR NOTICE Backtrace:  (/host.php[117]:host_reload_query(), /host.php[525]:run_data_query(), /lib/data_query.php[106]:query_snmp_host(), /lib/data_query.php[833]:CactiErrorHandler())

Pls help.. I did installed the latest version of cacti and mikrotik plugin too. same issue..

**Comment by WAMPerera** [comment]
If I go with default  data input method --> to script server,


Total: 0.000000, Delta: 0.000000, Found data query XML file at '/usr/share/cacti/plugins/mikrotik/templates/resource/script_server/mikrotik_queues.xml'
--
Total: 0.000000, Delta: 0.000000, Running Data Query [11].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.130000, Delta: 0.130000, ERROR: Data Query returned no indexes.

**Comment by tribudir** [comment]
Same issue on cacti 1.2.7

`

Total: 0.000000,  Delta: 0.000000, Found data query XML file at  '/var/www/mrtg2/plugins/mikrotik/templates/resource/script_server/mikrotik_queues.xml' Total: 0.000000, Delta: 0.000000, Running Data Query [11]. Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server]. Total: 0.000000, Delta: 0.000000, XML file parsed ok. Total: 0.090000, Delta: 0.090000, Data Query returned no indexes. Total: 0.090000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported Total: 0.090000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/mrtg2/plugins/mikrotik/templates/scripts/ss_mikrotik_queues.php  '6' 'num_indexes'' Total: 0.190000, Delta: 0.090000, ERROR: Data Query returned no indexes. | Total: 0.000000,  Delta: 0.000000, Found data query XML file at  '/var/www/mrtg2/plugins/mikrotik/templates/resource/script_server/mikrotik_queues.xml' | Total: 0.000000, Delta: 0.000000, Running Data Query [11]. | Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server]. | Total: 0.000000, Delta: 0.000000, XML file parsed ok. | Total: 0.090000, Delta: 0.090000, Data Query returned no indexes. | Total: 0.090000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported | Total: 0.090000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/mrtg2/plugins/mikrotik/templates/scripts/ss_mikrotik_queues.php  '6' 'num_indexes'' | Total: 0.190000, Delta: 0.090000, ERROR: Data Query returned no indexes.
-- | -- | -- | -- | -- | -- | -- | -- | --
Total: 0.000000,  Delta: 0.000000, Found data query XML file at  '/var/www/mrtg2/plugins/mikrotik/templates/resource/script_server/mikrotik_queues.xml'
Total: 0.000000, Delta: 0.000000, Running Data Query [11].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.090000, Delta: 0.090000, Data Query returned no indexes.
Total: 0.090000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported
Total: 0.090000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/mrtg2/plugins/mikrotik/templates/scripts/ss_mikrotik_queues.php  '6' 'num_indexes''
Total: 0.190000, Delta: 0.090000, ERROR: Data Query returned no indexes.
`

**Comment by tribudir** [comment]
Same issue on cacti 1.2.7

Can't create simple queue graph

Total: 0.000000, Delta:  0.000000, Found data query XML file at  '/var/www/mrtg2/plugins/mikrotik/templates/resource/script_server/mikrotik_queues.xml'
--
Total: 0.000000, Delta: 0.000000, Running Data Query [11].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.090000, Delta: 0.090000, Data Query returned no indexes.
Total: 0.090000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported
Total: 0.090000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/mrtg2/plugins/mikrotik/templates/scripts/ss_mikrotik_queues.php  '6' 'num_indexes''
Total: 0.190000, Delta: 0.090000, ERROR: Data Query returned no indexes.

**Comment by TheWitness** [comment]
Should be resolved now.
