### ISSUE TITLE
cannot find MikroTik - Queues

### ISSUE THREAD

**Issue by karkaaa** [Cacti/plugin_mikrotik#39]
Hello,

Then i debug

>  Data Query [MikroTik - Queues]

Get this:

```
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/opt/cacti/plugins/mikrotik/templates/resource/script_server/mikrotik_interfaces.xml'
Total: 0.000000, Delta: 0.000000, Running Data Query [11].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.060000, Delta: 0.060000, Data Query returned no indexes.
Total: 0.060000, Delta: 0.000000, <arg_num_indexes> exists in XML file but no data returned., 'Index Count Changed' not supported
Total: 0.060000, Delta: 0.000000, Executing script for num of indexes '"/usr/bin/php" -q /opt/cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_interfaces.php '8' 'num_indexes''
Total: 0.110000, Delta: 0.050000, ERROR: Data Query returned no indexes.
```

How to fix and add this queues:
![image](https://user-images.githubusercontent.com/34538939/72219820-dd9f0c80-3552-11ea-93de-14803da3dcab.png)

My MikroTik adress is http**s**://192.168.88.1:**8443**/graphs/ 
maybe it is a problem?

Mikrotik RBD52G-5HacD2HnD
Cacti version: 1.2.8
Spine version: 1.2.2
Mikrotik plugin version: 2.4

Thank you.

**Comment by karkaaa** [comment]
solved

**Comment by pablo0582** [comment]
how do I solve it?

**Comment by TheWitness** [comment]
You have to turn on Queue Collection under settings.

**Comment by damarmuhisa** [comment]
> You have to turn on Queue Collection under settings.

where is queue collection under setting option? i have same problem.
on cacti 1.2.22 with pluggin 2.4

![image](https://user-images.githubusercontent.com/119432469/204576135-9b7d190a-ac84-4f21-a00f-9bb983a59e34.png)
![image](https://user-images.githubusercontent.com/119432469/204576306-316152e9-1238-450c-b521-087b7e751d88.png)

**Comment by TheWitness** [comment]
Console > Setting > Mikrotik
