### ISSUE TITLE
CMDPHP ERROR:RouterOS

### ISSUE THREAD

**Issue by karkaaa** [Cacti/plugin_mikrotik#40]
Hello,

I get this error:
![image](https://user-images.githubusercontent.com/34538939/75255659-f275ed80-57ea-11ea-9efa-cbbebd29e6e1.png)

Mikrotik RBD52G-5HacD2HnD
Cacti version: 1.2.8
Spine version: 1.2.2
Mikrotik plugin version: 2.4

Thank you.

**Comment by TheWitness** [comment]
Mikrotik plugin requires the API user and password.  You can set that user and password from Console > Management > Devices.

You either did not provide one, or it's wrong.

**Comment by karkaaa** [comment]
I can't control Mikrotik because it is the provider router. Maybe i can ignore this errors?

**Comment by TheWitness** [comment]
Sure, that would be an enhancement request

**Comment by TheWitness** [comment]
Sure, that would be an enhancement request

**Comment by TheWitness** [comment]
This should be resolved now.  There is a new settings under Console > Configuration > Settings > Mikrotik to disable API polling.  Just uncheck it.
