### ISSUE TITLE
RouterOS API Call Timed Out. Check for an invalid API password!

### ISSUE THREAD

**Issue by mehransalehian** [Cacti/plugin_mikrotik#43]
Hi;
I have a problem connecting Mikrotik through API ;
on my mikrotik "IP->Services API is active on port 8728 "
and I have a readonly user on my mikrotik.
My mikrotik is CCR1036 and software version is 6.47 the last version
my cacti find all my graphs and works well ,but cannot connect to mikrotik by "MikroTik Credentials"and it says : "Connection Failed"
I think maybe this version of cacti template cannot connect to API with new versions in mikrotik.

![erroe cacti log](https://user-images.githubusercontent.com/44561859/84398673-3c35e880-abce-11ea-9b4c-8435e8f0de66.JPG)

![API mikrotik](https://user-images.githubusercontent.com/44561859/84398986-9a62cb80-abce-11ea-9079-bf2dfb0efa63.JPG)

![user pass](https://user-images.githubusercontent.com/44561859/84398691-422bc980-abce-11ea-997a-2662203d864f.JPG)

**Comment by TheWitness** [comment]
What is your RouterOS version?  Older versions may not be tested.

**Comment by TheWitness** [comment]
Okay, I see the version now.

**Comment by TheWitness** [comment]
I would try to access the router using ssh first.  If you can get to it through ssh, then you should be able to access it through the API.

**Comment by TheWitness** [comment]
If you have setup the router for SSH access using a key, this might be problematic, I mean to login with a password.

**Comment by TheWitness** [comment]
No response.

**Comment by coder-binary1** [comment]
@TheWitness I have the same issue, I put in the correct password and port. but the Connection Result is failed

**Comment by coder-binary1** [comment]
@TheWitness  I have the same issue, I put in the correct password and port. but the Connection Result is failed

CMDPHP ERROR: Device[[Deveice name](http://-ip-/cacti/host.php?action=edit&id=2)] for RouterOS API Call Timed Out. Check for an invalid API password!

**Comment by TheWitness** [comment]
Did you fill out as below?

![image](https://user-images.githubusercontent.com/1439914/208269829-b4ef2825-7ca7-4aef-a063-6d41cd83af12.png)

What version of RouterOS?

**Comment by TheWitness** [comment]
Are you running through SSL or simply clear connection?

**Comment by coder-binary1** [comment]
> u running through SSL or simply clear connection?

I tried will default non-ssl API port. and also input the correct credentials

**Comment by coder-binary1** [comment]
@TheWitness 
![image](https://user-images.githubusercontent.com/96922458/208360859-98119a1a-0e86-4a50-92b9-e5de61d021f6.png)

another issue is, I can't use those graph anymore, which was usable before installation.

**Comment by coder-binary1** [comment]
I tried with both 1.2.22 and 1.2.23 version, but nothing is working

**Comment by coder-binary1** [comment]
@TheWitness Now its working after changing default port

**Comment by coder-binary1** [comment]
but templet is not working
![image](https://user-images.githubusercontent.com/96922458/208383232-43b891fd-28f1-4826-be16-966084229508.png)

**Comment by TheWitness** [comment]
The question was are you running with ssl enabled?

**Comment by coder-binary1** [comment]
No, I just port 8728

**Comment by TheWitness** [comment]
Why don't you do a TCP dump and send the output to thewitness at cacti.net

**Comment by TheWitness** [comment]
Just that port nothing else else.

**Comment by TheWitness** [comment]
Oh, I did not see that you got it working.  What Cacti release?

**Comment by coder-binary1** [comment]
Cacti Version 1.2.23

**Comment by skywalker-znz** [comment]
I have the same issue, Centos7, Cacti 1.2.21, plugin 2.6. and template error. 
Sorry for my ignorance, where do I put the API credentials, I could not find mikrotik login info. Thank you.

**Comment by skywalker-znz** [comment]
disabling and enabling the plugin fixed this, but the interface are still showing errors.

**Comment by skywalker-znz** [comment]
on dev, template/script and resources directory are empty, I tried to roll back to 2.4, the script runs but interface returns 0. Thank you.

**Comment by TheWitness** [comment]
There are two packages in the `install/templates` directory of the Cacti 1.2.x branch.  You should install those and the reindex your devices followed by repopulating the poller cache.

**Comment by TheWitness** [comment]
All the resources and script files have been moved to the normal locations.

**Comment by skywalker-znz** [comment]
Thank you, I tried to install it from Cacti 1.2 template, but end up with this error, 
php -q /var/lib/cacti/cli/import_package.php --filename=/usr/share/cacti/plugins/mikrotik/templates/MikroTik_Device.xml.gz
Read 176931 bytes of Package data
ERROR: file /usr/share/cacti/plugins/mikrotik/templates/MikroTik_Device.xml.gz import process failed due to errors with the XML file

**Comment by TheWitness** [comment]
Okay, it's likely has the new key we are using in 1.2.23.  I'll check that this morning. Do me a favor and don't install it.  I've been waiting for the 1.2.23 release before doing a formal re-release.

**Comment by skywalker-znz** [comment]
I started from scratch, Ubuntu 22.04, Cacti 1.2.22, installed the plugin, and landed with the same error on interfaces. If I copy the files to /the resource directory, Cacti find the file but still complains on the interface returning empty. Install is pretty straight forward, not sure where I am going wrong. Thank you for your time. 


Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/plugins/mikrotik/templates/resource/script_server/mikrotik_interfaces.xml'
--
Total: 0.000000, Delta: 0.000000, Running Data Query [27].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.070000, Delta: 0.070000, Data Query returned no indexes.
Total: 0.070000, Delta: 0.000000, <arg_num_indexes> exists in XML file but no data returned., 'Index Count Changed' not supported
Total: 0.070000, Delta: 0.000000, Executing script for num of indexes '"/usr/bin/php" -q /var/www/html/cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_interfaces.php '2' 'num_indexes''
Total: 0.150000, Delta: 0.070000, ERROR: Data Query returned no indexes.

**Comment by coder-binary1** [comment]
@TheWitness I installed the packages from install/templates, and resources and script files have been moved to the correct location. but still there is data queue error occuring.

**Comment by coder-binary1** [comment]
@TheWitness I installed the packages from install/templates, and resources and script files have been moved to the correct location. but still, there is data queue error occurring.
