### ISSUE TITLE
XML parse error on Import Template

### ISSUE THREAD

**Issue by rirozizo** [Cacti/plugin_mikrotik#44]
**Describe the bug**

I get an XML parse error when I try to import the MikroTik_Device.xml file

**To Reproduce**
1. Go to 'Import/Export'
2. Click on 'Import Templates'
3. Click on 'Select a File'
4. Select the 'MikroTik_Device.xml' file
5. Click on 'Import'

**Expected behavior**
It should import the template, maybe give me a new device type?

**Screenshots**

![cacti](https://user-images.githubusercontent.com/1951499/85405720-7fe30780-b569-11ea-9825-ec1fd2b0fdd2.png)

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: Cacti v1.2.12

**Additional context**
Cacti Logs say the following:

```
2020-06-23 15:43:27 - IMPORT ERROR: Import or Preview failed!
2020-06-23 15:43:27 - IMPORT parse_xml_hash ERROR wrong hash format for hash: info
```

**Comment by rirozizo** [comment]
Using SSH, I tried the following command:

```
php -q /<cactidir>/cli/import_template.php --filename=/<cactidir>/site/plugins/mikrotik/templates/MikroTik_Device.xml --with-template-rras
```

It leads to the same error in Cacti's Log:
```
IMPORT parse_xml_hash ERROR wrong hash format for hash: info
```

**Comment by frituurpan** [comment]
I made the same mistake, but if you use `import_package.php`, it works.

`php cli/import_package.php --filename=/cacti/plugins/mikrotik/templates/MikroTik_Device.xml`

https://github.com/Cacti/cacti/issues/3320#issuecomment-596222571

**Comment by TheWitness** [comment]
Import package for an XML file seems odd.  If it was an xml.gz file, then all is good.
