### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by razvanzeces** [Cacti/plugin_mikrotik#49]
Hello,

I've just installed plugin on Cacti 1.2.15 and I'm receiving this errors on the Log section.

What could be the reason? I can see that the plugin retrieved the Mikrotik devices accordingly.
![mikrotik](https://user-images.githubusercontent.com/56639628/98674790-fbe7bb80-2361-11eb-9df3-31630865267f.png)

**Comment by TheWitness** [comment]
Check you log from the moment of install for table creation errors.  What version of MySQL/MariaDB?

**Comment by razvanzeces** [comment]
@TheWitness this is the first time when the issue appeared.

![logfirst](https://user-images.githubusercontent.com/56639628/98676987-0a83a200-2365-11eb-8255-007a1cf896d4.png)

MySQL version it's: Server version: 10.1.47-MariaDB-0+deb9u1 Debian 9.13

**Comment by razvanzeces** [comment]
@TheWitness error it's reporting ok. That table doesn't exist under DB cacti.

**Comment by razvanzeces** [comment]
So the conclusion it's that the installer doesn't create the table that needed to be create -> "cacti.plugin_mikrotik_storage".

I created it manually, the issue still appears. 

Any ideeas?

**Comment by TheWitness** [comment]
Yea, got Console > Utilities > Technical Support, bottom of the general tab.  You have some data base settings wrong.  I'm thinking innodb_file_format and innodb_large_prefix are wrong.   After you change those two setting, you will have to restart MariaDB, then reinstall the plugin.

**Comment by razvanzeces** [comment]
I solved it how you suggested.

Thanks for help.
