### ISSUE TITLE
Error on log when enable plugin

### ISSUE THREAD

**Issue by sijiq** [Cacti/plugin_mikrotik#52]
I got error on log when enable plugin

2021/05/29 05:53:39 - CMDPHP SQL Backtrace: (/plugins.php[74]:api_plugin_install(), /lib/plugins.php[675]:plugin_mikrotik_install(), /plugins/mikrotik/setup.php[41]:mikrotik_setup_table(), /plugins/mikrotik/setup.php[312]:db_execute(), /lib/database.php[238]:db_execute_prepared())
--
2021/05/29 05:53:39 - CMDPHP ERROR: A DB Exec Failed!, Error: Index column size too large. The maximum column size is 767 bytes.

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by netniV** [comment]
You need to enable large prefixes on your MySQL installation.  Cacti itself should warn you about that whenever you upgrade.
