### ISSUE TITLE
100% CPU load for random pooler_mikrotik.php

### ISSUE THREAD

**Issue by MegaAndrey** [Cacti/plugin_mikrotik#53]
Fresh installed Cacti and last version of mikrotik plugin.
After a while I observe this:
https://i.imgur.com/3xNn2MI.png

How can I investigate this and resolve the issue?

**Comment by TheWitness** [comment]
Better find a better place to post a link.

**Comment by MegaAndrey** [comment]
![3xNn2MI](https://user-images.githubusercontent.com/12414028/145028291-e4c187a0-7ca8-4d31-97dc-c4f25aa251e8.png)

**Comment by TheWitness** [comment]
The way I've written just about all my plugins is to have a poller* file in the plugin folder.  You can run it by hand with the `--debug` flag for some clues. Did you set your API user and password on the device page?

**Comment by MegaAndrey** [comment]
Is it under section MikroTik Credentials? Because I can't find anything else on Device page.
This happened when we have changed Description on some devices.

**Comment by MegaAndrey** [comment]
DEBUG: Elapsed: 0, Message: Polling System from 'jet-mkt-pop-1002627[172.21.0.115]'
DEBUG: Elapsed: 1, Message: Beginning Processing for 'jet-mkt-pop-1002627[172.21.0.115]', Table 'users'
DEBUG: Elapsed: 1, Message: Polling users from 'jet-mkt-pop-1002627[172.21.0.115]'
DEBUG: Elapsed: 1, Message: Polled: jet-mkt-pop-1002627, OID: .1.3.6.1.4.1.14988.1.1.5.1.1.2, Size: 0
DEBUG: Elapsed: 1, Message: No Index Information for OID: .1.3.6.1.4.1.14988.1.1.5.1.1.3 on jet-mkt-pop-1002627 returning
DEBUG: Elapsed: 1, Message: Beginning Processing for 'jet-mkt-pop-1002627[172.21.0.115]', Table 'trees'
DEBUG: Elapsed: 1, Message: Polling trees from 'jet-mkt-pop-1002627[172.21.0.115]'
DEBUG: Elapsed: 1, Message: No Index Information for OID: .1.3.6.1.4.1.14988.1.1.2.2.1.2 on jet-mkt-pop-1002627 returning
DEBUG: Elapsed: 1, Message: Beginning Processing for 'jet-mkt-pop-1002627[172.21.0.115]', Table 'queues'
DEBUG: Elapsed: 1, Message: Polling queues from 'jet-mkt-pop-1002627[172.21.0.115]'
DEBUG: Elapsed: 1, Message: No Index Information for OID: .1.3.6.1.4.1.14988.1.1.2.1.1.2 on jet-mkt-pop-1002627 returning

on this it freezes and takes 100% CPU load.

**Comment by TheWitness** [comment]
Follow the code.  What step is it stuck on?

**Comment by TheWitness** [comment]
Next step is pppoe.  Are you using pppoe?  Is the API properly setup?

![image](https://user-images.githubusercontent.com/1439914/147250606-a1f4249f-3284-4705-9ee1-e8930081ae26.png)

Edit the device, and towards the bottom of the page, you should find this:

![image](https://user-images.githubusercontent.com/1439914/147250808-dd6cc64c-c102-4c93-823f-e5c7743fd310.png)

**Comment by MegaAndrey** [comment]
So, problem solved by re-creating devices and graphs.
