### ISSUE TITLE
Queues not updating with discovery button

### ISSUE THREAD

**Issue by MegaAndrey** [Cacti/plugin_mikrotik#54]
I found interesting (maybe) bug.

So if I want to create new graph on cacti with Data Query [MikroTik - Queues], I added simple queue on mkt, then Create graph for this device on cacti, press button Discovery (or update, green circular arrows) and nothing happens, the newly created queue does not appear in the list. After about 3-5 min I press this button again and it appears, is it normal?

**Comment by TheWitness** [comment]
Yea, that's normal.  The collection happens through the cacti poller which be default is every 5 minutes.  Use use either 1 minute or 30 seconds these days since I only have ~ 100 devices to monitor.
