### ISSUE TITLE
ERROR PHP NOTICE in Plugin 'mikrotik': A non well formed numeric value encountered in file: /var/www/html/cacti/plugins/mikrotik/poller_mikrotik.php on line: 1517

### ISSUE THREAD

**Issue by ghost** [Cacti/plugin_mikrotik#55]
ERROR PHP NOTICE in Plugin 'mikrotik': A non well formed numeric value encountered in file: /var/www/html/cacti/plugins/mikrotik/poller_mikrotik.php on line: 1517 
 CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mikrotik/poller_mikrotik.php[138]:checkHost(), /plugins/mikrotik/poller_mikrotik.php[796]:collect_dhcp_details(), /plugins/mikrotik/poller_mikrotik.php[1302]:uptimeToSeconds(), /plugins/mikrotik/poller_mikrotik.php[1517]:CactiErrorHandler()) 
 ERROR PHP NOTICE in Plugin 'mikrotik': A non well formed numeric value encountered in file: /var/www/html/cacti/plugins/mikrotik/poller_mikrotik.php on line: 1516 
CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mikrotik/poller_mikrotik.php[138]:checkHost(), /plugins/mikrotik/poller_mikrotik.php[796]:collect_dhcp_details(), /plugins/mikrotik/poller_mikrotik.php[1302]:uptimeToSeconds(), /plugins/mikrotik/poller_mikrotik.php[1516]:CactiErrorHandler())

- OS: Ubuntu

- Browser firefox

- Version 1.2.20

**Comment by TheWitness** [comment]
Please update to the develop version of MicroTik and report back.  This issue may have already be fixed.  The line numbers for sure do not match.  Thanks!

**Comment by ghost** [comment]
CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php[136]:getLatestVersion(), /plugins/mikrotik/poller_mikrotik.php[146]:file_get_contents(), CactiErrorHandler()) 
ERROR PHP WARNING in Plugin 'mikrotik': file_get_contents(http://upgrade.mikrotik.com/routeros/LATEST.6): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in file: /var/www/html/cacti/plugins/mikrotik/poller_mikrotik.php on line: 146 
 CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php[136]:getLatestVersion(), /plugins/mikrotik/poller_mikrotik.php[146]:file_get_contents(), CactiErrorHandler()) 
 ERROR PHP WARNING in Plugin 'mikrotik': file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in file: /var/www/html/cacti/plugins/mikrotik/poller_mikrotik.php on line: 146

**Comment by TheWitness** [comment]
Oh, that's interesting.

**Comment by TheWitness** [comment]
So, it would appear that the cacti install does not have access to the internet or an internet dns service?

**Comment by ghost** [comment]
on cacti server i ping 8.8.8.8 and google.com , and that's work.
but errors exist.
CMDPHP PHP ERROR NOTICE Backtrace: (/script_server.php[191]:fputs(), CactiErrorHandler()) 
ERROR PHP NOTICE: fputs(): write of 53 bytes failed with errno=32 Broken pipe in file: /var/www/html/cacti/script_server.php on line: 191

**Comment by TheWitness** [comment]
Use spine instead of cmd.php and increase your threads.  This is a sign that the script has timed out I think.

Did you update mikrotik?

**Comment by ghost** [comment]
hi
sorry , i install new cacti server and test develop version. it was ok
thanks

**Comment by ghost** [comment]
- CMDPHP SQL Backtrace: (/cli/add_graphs.php[648]:db_fetch_assoc(), /lib/database.php[501]:db_fetch_assoc_prepared(), /lib/database.php[515]:db_execute_prepared()) 

 CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 

CMDPHP SQL Backtrace: (/cli/add_graphs.php[648]:db_fetch_assoc(), /lib/database.php[501]:db_fetch_assoc_prepared(), /lib/database.php[515]:db_execute_prepared())

**Comment by TheWitness** [comment]
That's more of a Cacti issue and likely a use problem with the CLI.  I'm going to prevent it from logging the backtrace, but it's likely you are specifying the wrong values.

**Comment by TheWitness** [comment]
Going to close this one as you are mixing too many issues.  You should open each issue separately in the appropriate location.  Thanks though.  The `add_graphs.php` bug needed to be taken care of.  Note that MySQL/MariaDB regex's are not compatible with Perl regex's sadly.
