### ISSUE TITLE
Spikes on MikroTik - Queue - Traffic

### ISSUE THREAD

**Issue by MegaAndrey** [Cacti/plugin_mikrotik#56]
The problem is that on all queue graphs I observe unusual spikes. And I can't use killspike because this template is not visible in the settings list. An interesting fact is that on all graphs these bursts occur at the same time.

Any advice would be helpful.

![chrome_oSf2QMGcQm](https://user-images.githubusercontent.com/12414028/156867984-facce547-dec3-46ea-a4ba-fe4d813cdef3.png)

![chrome_VuMiEgHcxq](https://user-images.githubusercontent.com/12414028/156868016-d60209e0-0697-42c6-9590-68961346d0bb.png)

**Comment by MegaAndrey** [comment]
I also noticed that the traffic count is wrong.
![winbox_FmVw5KGbQ9](https://user-images.githubusercontent.com/12414028/156872027-376d75b7-5f66-4ef0-a36e-29d4434314c2.png)

![chrome_xph2NhuqCb](https://user-images.githubusercontent.com/12414028/156872061-587fc751-8148-49ee-a301-cddd03709ad9.png)

**Comment by TheWitness** [comment]
Been so long since I've worked with these.  My guess is that the RRDfiles are using a GAUGE when they should be using a COUNTER.  Can you confirm?

**Comment by MegaAndrey** [comment]
Not really, this problem was due to incorrect data count, solved by graph recreating.
