### ISSUE TITLE
PLUGIN WARNING: Function does not exist config_form with function mikrotik_config_form

### ISSUE THREAD

**Issue by densenator** [Cacti/plugin_mikrotik#61]
If i set Generic Log Level to DEBUG, i always see that error:

PLUGIN WARNING: Function does not exist config_form with function mikrotik_config_form

I don't know what function it's mean, but i hope it's helped for solve this error.

**Comment by TheWitness** [comment]
This has been resolved.  You will need to do an upgrade once I update the INFO file.
