### ISSUE TITLE
install fails with SQL Backtrace error

### ISSUE THREAD

**Issue by zachs1008** [Cacti/plugin_mikrotik#64]
Brand new clean install of Cacti and I am attempting to install the MikroTik plugin.  I have imported the provided templates successfully.  When clicking the install plugin button, it flashes and does not install.  Viewing the logs, these two lines are present. 

2022-07-13 08:59:46 - CMDPHP SQL Backtrace: (/plugins.php[78]:api_plugin_install(), /lib/plugins.php[725]:db_execute_prepared())
2022-07-13 08:59:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'name' cannot be null

cacti version: 1.2.21
OS: Ubuntu 20.04

**Comment by TheWitness** [comment]
@zachs1008, Did you get this fixed?

**Comment by zachs1008** [comment]
I started over from scratch as was able to get things going.

**Comment by TheWitness** [comment]
@zachs1008,

Cool.  I suspect you have the plugin folder named incorrectly.  Glad you got it working.

TW
