### ISSUE TITLE
simple queue data issue

### ISSUE THREAD

**Issue by emoqbao** [Cacti/plugin_mikrotik#66]
1. MikroTik - Queues get the script server and SNMP data do not match, the time and quantity are different, as can be seen from the bulge in the figure below, the sum of the traffic of the first and fourth graphs I monitor is the traffic of ether1
![image](https://user-images.githubusercontent.com/110520892/182537938-2ad552fb-4fb7-41d9-96d8-89ad4e30aa46.png)
![image](https://user-images.githubusercontent.com/110520892/182538059-7f60300b-f5a0-495c-ac40-f6440e24d285.png)

2. Mikrotik simple queues modify the Name, Cacti will not automatically update the name but will regenerate a new row and new diagram, which is not so convenient

**Comment by TheWitness** [comment]
Yea, this is true.  We may have to make the spice API more accessible from the GUI to correct this. 

In the mean time, look into the CLI folder for splice*.php and use it for the repair.
