### ISSUE TITLE
Host Template of Mikrotik Issue #ipacmikro.xml

### ISSUE THREAD

**Issue by nomanjim** [Cacti/plugin_mikrotik#67]
OS: ubuntu-22.04.1-live-server-amd64
Cacti Version: Latest 1.2.22

Having trouble with the host template issue in the Mikrotik plugin ...
It shows a missing file of ipacmikro.xml but when I upload the ipacmikro.xml file, it shows the template now uploaded but I can't make it worthy .it because it never showed up even in data query or template or else. I can't find where the problem is ...
Even if I upload all necessary XML files it never showed that its familiar to OS as its not change color (Not having green color that OS can recognise )
The plugin has been installed but I can't use the host template to make Mikrotik queue MRTG. 
Need help. 
![cacti 1 2 22](https://user-images.githubusercontent.com/119280664/206092911-56280132-ef4d-4c42-b513-97cd40becaba.jpg)

![xml](https://user-images.githubusercontent.com/119280664/206092997-6aaf38b4-aa8b-4fe6-a1cd-8ec4c3fe58ef.jpg)

**Comment by TheWitness** [comment]
This was addressed on the forums and that was the right location for it to be addressed
