### ISSUE TITLE
Data Queries is not indexed

### ISSUE THREAD

**Issue by coder-binary1** [Cacti/plugin_mikrotik#68]
I install the latest cacti 1.2.23 on a fresh ubuntu 22.04.

Then I install the Mikrotik plugin and the Mikrotik through API.

 ****the Graph Templates are indexed and start graphing but the Data Queries are not indexed.**

![image](https://user-images.githubusercontent.com/96922458/208527585-53fc34d9-f751-4a45-86ab-04a990049df6.png)

 ****And on the graph creation page, I found this permission error.**

![image](https://user-images.githubusercontent.com/96922458/208527869-f973e697-54ad-4dbc-83a3-aaeab5f18274.png)

I need assistance from you to solve this issue.

**Comment by TheWitness** [comment]
You have to set the API Username and Password for each device, and then Enable Data Collection and Frequencies from `Console > Configuration > Settings > MicroTik`.  After that, within a few minutes, you should be able to Re-Index the device.

**Comment by TheWitness** [comment]
![image](https://user-images.githubusercontent.com/1439914/208548615-2272063f-99a6-4e57-be50-15e154a7f565.png)

and

![image](https://user-images.githubusercontent.com/1439914/208548686-cd7f8f40-931f-4105-9d50-c80a718dffd8.png)

**Comment by coder-binary1** [comment]
**Everything was same as you suggest, but it didn't work,**

![image](https://user-images.githubusercontent.com/96922458/208647159-bd6c1b6d-d4ea-441a-8cea-e6069fe1984b.png)

**Comment by coder-binary1** [comment]
@TheWitness is there any solution for this issue?

**Comment by skywalker-znz** [comment]
Same issue here, Cacti 1.2.23 on a fresh Ubuntu 22.04, earlier was on Centos 7. Thank you.

**Comment by TheWitness** [comment]
In 1.2.23, you can import these two from the GUI `Console > Import/Export > Import Package`.  Try that.

[MikroTik_Switch_SWOS.xml.gz](https://github.com/Cacti/plugin_mikrotik/files/10336928/MikroTik_Switch_SWOS.xml.gz)
[MikroTik_Device.xml.gz](https://github.com/Cacti/plugin_mikrotik/files/10336929/MikroTik_Device.xml.gz)

**Comment by skywalker-znz** [comment]
@TheWitness I just tried that, same results. Its either a bug or some steps I am missing. 

![empty](https://user-images.githubusercontent.com/121727726/210370840-80f46681-8cc4-4607-b945-2eeca9c24781.png)

**Comment by TheWitness** [comment]
Run this command:

```sql
select * from plugin_mikrotik_interfaces;
```

**Comment by TheWitness** [comment]
This might be better:

```sql
 select * from plugin_mikrotik_interfaces where TxBytes>0 LIMIT 2\G
```

**Comment by TheWitness** [comment]
That way you can see the forest from the tree's.  Then, in the Cacti.log you should find these entries:

![image](https://user-images.githubusercontent.com/1439914/210372121-c5f7a470-61a6-4c10-a266-bdc81c549a84.png)

**Comment by skywalker-znz** [comment]
Hi @TheWitness  where do I run this command,  select * from plugin_mikrotik_interfaces where TxBytes>0 LIMIT 2\G

**Comment by TheWitness** [comment]
From MySQL command line.

**Comment by TheWitness** [comment]
Note though that my cacti.log says I've got 26 interfaces updated every minute.

**Comment by skywalker-znz** [comment]
MariaDB [cacti]> select * from plugin_mikrotik_interfaces where TxBytes>0 LIMIT 2\G
Empty set (0.001 sec)
MariaDB [cacti]> select * from plugin_mikrotik_interfaces;
Empty set (0.001 sec)

I don't have any devices on this install, just 1 for testing, I dont see any mikrotik as I cannot graph any interfaces.

**Comment by skywalker-znz** [comment]
![empty 2](https://user-images.githubusercontent.com/121727726/210374513-d4c00787-4b3d-4b65-966d-109e6b61468a.png)

**Comment by TheWitness** [comment]
What about your Cacti log?

**Comment by skywalker-znz** [comment]
![log](https://user-images.githubusercontent.com/121727726/210375786-3a732cfb-5e2a-45c9-a3ff-e66765a8cd84.png)

**Comment by skywalker-znz** [comment]
![part 1](https://user-images.githubusercontent.com/121727726/210377489-cba0411d-17d7-4a23-862e-230395554dcf.png)
![part 2](https://user-images.githubusercontent.com/121727726/210377495-36b721b1-6619-4d67-aaab-2ad08cfa6c6f.png)

**Comment by TheWitness** [comment]
Switch to low until your Cacti log looks like the one I posted.

**Comment by skywalker-znz** [comment]
03-Jan-2023 17:45:18 - SYSTEM STATS: Time:17.2323 Method:cmd.php Processes:1 Threads:1 Hosts:2 HostsPerProcess:2 DataSources:33 RRDsProcessed:33
--
03-Jan-2023 17:45:10 - 2 WARNING: SNMP Error:'snmp2_get(): No response from 192.168.1.1', Device:'192.168.1.1', OID:'.1.3.6.1.4.1.9.9.150.1.1.1.0'

03-Jan-2023 17:45:04 - 2 WARNING: SNMP Error:'snmp2_get(): No response from 192.168.1.1', Device:'192.168.1.1', OID:'1.3.6.1.2.1.4.24.3.0'

Could this be issue?

**Comment by skywalker-znz** [comment]
When i go to Mikrotik tab, I dont see any device, but I see graphs on graphs tab, Should it not show the devices on mikrotik tab?

**Comment by skywalker-znz** [comment]
![mikrotik](https://user-images.githubusercontent.com/121727726/210384247-ee1a25ec-6b53-416f-8dc2-ba3f42186cb5.png)

**Comment by TheWitness** [comment]
Why don't you answer my previous question?

**Comment by TheWitness** [comment]
I'm going to close this knowing now what is going on.  I see that you posted on the forums as well.  Let's continue the discussion there.

**Comment by skywalker-znz** [comment]
Thank you, I have been going round and round on this one. :)

**Comment by coder-binary1** [comment]
Here is my output


MariaDB [cacti]> select * from plugin_mikrotik_interfaces;
Empty set (0.001 sec)

**Comment by coder-binary1** [comment]
Here is my output

MariaDB [cacti]> select * from plugin_mikrotik_interfaces;
      0 |        0 |           0 |         0 |          0 |          0 |            0 |             0 |         0 |            0 |             0 |             0 |              0 |               0 |              0 |            0 |              0 |          0 |              0 |              0 |               0 |             0 |             0 |            0 |              0 |                0 |              0 |                 0 |           0 |         0 |          0 |            0 |             0 |         0 |            0 |             0 |             0 |              0 |               0 |              0 |            0 |              0 |          0 |              0 |             0 |              0 |                0 |                  0 |                  0 |               0 |             0 |                  0 |                   0 |                 0 |         0 |           0 |              0 |            0 |             0 |              0 |             0 |              0 |          0 |             0 |              0 |              0 |               0 |                0 |               0 |             0 |               0 |           0 |               0 |               0 |                0 |              0 |              0 |             0 |               0 |                 0 |               0 |                  0 |            0 |          0 |              0 |             0 |              0 |          0 |             0 |              0 |              0 |               0 |                0 |               0 |             0 |               0 |           0 |               0 |              0 |               0 |                 0 |                   0 |                   0 |                0 |              0 |                   0 |                    0 |                  0 |          0 |            0 |               0 |             0 |              0 | 2023-01-04 04:30:07 |       1 |
+---------+----------+------------------------------------+----------------+-------------+------------+----------+------------+------------+------------+-------------+--------------+-------------+-----------+-------------+---------+-------------+-------------+--------------+------------+------------+-----------+-------------+---------------+-------------+----------------+----------+---------+----------------+-------------+------------+--------+-----------+------------+------------+-------------+--------------+-------------+-----------+-------------+---------+-------------+------------+-------------+---------------+-----------------+-----------------+--------------+------------+-----------------+------------------+----------------+--------+----------+-------------+-----------+------------+------------+--------------+---------------+-----------+--------------+---------------+---------------+----------------+-----------------+----------------+--------------+----------------+------------+----------------+----------------+-----------------+---------------+---------------+--------------+----------------+------------------+----------------+-------------------+-------------+-----------+------------+--------------+---------------+-----------+--------------+---------------+---------------+----------------+-----------------+----------------+--------------+----------------+------------+----------------+---------------+----------------+------------------+--------------------+--------------------+-----------------+---------------+--------------------+---------------------+-------------------+-----------+-------------+----------------+--------------+---------------+----------------+---------------+----------------+------------+---------------+----------------+----------------+-----------------+------------------+-----------------+---------------+-----------------+-------------+-----------------+-----------------+------------------+----------------+----------------+---------------+-----------------+-------------------+-----------------+--------------------+--------------+------------+----------------+---------------+----------------+------------+---------------+----------------+----------------+-----------------+------------------+-----------------+---------------+-----------------+-------------+-----------------+----------------+-----------------+-------------------+---------------------+---------------------+------------------+----------------+---------------------+----------------------+--------------------+------------+--------------+-----------------+---------------+----------------+---------------------+---------+
348 rows in set (0.003 sec

MariaDB [cacti]> select * from plugin_mikrotik_interfaces where TxBytes>0 LIMIT 2\G
*************************** 1. row ***************************
             host_id: 3
               index: 1
                name: ETHER1
             RxBytes: 4468945834459
           RxPackets: 3996935894
          RxTooShort: 0
              RxTo64: 0
           Rx65to127: 0
          Rx128to255: 0
          Rx256to511: 0
         Rx512to1023: 0
        Rx1024to1518: 0
         Rx1519toMax: 0
           RxTooLong: 0
         RxBroadcast: 3129158
             RxPause: 0
         RxMulticast: 588443
         RxFCFSError: 0
        RxAlignError: 0
          RxFragment: 0
          RxOverflow: 0
           RxControl: 0
         RxUnknownOp: 0
       RxLengthError: 0
         RxCodeError: 0
      RxCarrierError: 0
            RxJabber: 0
              RxDrop: 749868
             TxBytes: 560932778324
           TxPackets: 2411573575
          TxTooShort: 0
              TxTo64: 0
           Tx65to127: 0
          Tx128to255: 0
          Tx256to511: 0
         Tx512to1023: 0
        Tx1024to1518: 0
         Tx1519toMax: 0
           TxTooLong: 0
         TxBroadcast: 3167189
             TxPause: 0
         TxMulticast: 0
          TxUnderrun: 0
         TxCollision: 0
       TxExCollision: 0
     TxMultCollision: 0
     TxSingCollision: 0
        TxExDeferred: 0
          TxDeferred: 0
     TxLateCollision: 0
    TxTotalCollision: 0
      TxPauseHonored: 0
              TxDrop: 0
            TxJabber: 0
         TxFCFSError: 0
           TxControl: 0
          TxFragment: 0
          curRxBytes: 13707973
        curRxPackets: 10928
       curRxTooShort: 0
           curRxTo64: 0
        curRx65to127: 0
       curRx128to255: 0
       curRx256to511: 0
      curRx512to1023: 0
     curRx1024to1518: 0
      curRx1519toMax: 0
        curRxTooLong: 0
      curRxBroadcast: 25
          curRxPause: 0
      curRxMulticast: 3
      curRxFCFSError: 0
     curRxAlignError: 0
       curRxFragment: 0
       curRxOverflow: 0
        curRxControl: 0
      curRxUnknownOp: 0
    curRxLengthError: 0
      curRxCodeError: 0
   curRxCarrierError: 0
         curRxJabber: 0
           curRxDrop: 0
          curTxBytes: 816197
        curTxPackets: 3511
       curTxTooShort: 0
           curTxTo64: 0
        curTx65to127: 0
       curTx128to255: 0
       curTx256to511: 0
      curTx512to1023: 0
     curTx1024to1518: 0
      curTx1519toMax: 0
        curTxTooLong: 0
      curTxBroadcast: 25
          curTxPause: 0
      curTxMulticast: 0
       curTxUnderrun: 0
      curTxCollision: 0
    curTxExCollision: 0
  curTxMultCollision: 0
  curTxSingCollision: 0
     curTxExDeferred: 0
       curTxDeferred: 0
  curTxLateCollision: 0
 curTxTotalCollision: 0
   curTxPauseHonored: 0
           curTxDrop: 0
         curTxJabber: 0
      curTxFCFSError: 0
        curTxControl: 0
       curTxFragment: 0
         prevRxBytes: 4468945834459
       prevRxPackets: 3996935894
      prevRxTooShort: 0
          prevRxTo64: 0
       prevRx65to127: 0
      prevRx128to255: 0
      prevRx256to511: 0
     prevRx512to1023: 0
    prevRx1024to1518: 0
     prevRx1519toMax: 0
       prevRxTooLong: 0
     prevRxBroadcast: 3129158
         prevRxPause: 0
     prevRxMulticast: 588443
     prevRxFCFSError: 0
    prevRxAlignError: 0
      prevRxFragment: 0
      prevRxOverflow: 0
       prevRxControl: 0
     prevRxUnknownOp: 0
   prevRxLengthError: 0
     prevRxCodeError: 0
  prevRxCarrierError: 0
        prevRxJabber: 0
          prevRxDrop: 749868
         prevTxBytes: 560932778324
       prevTxPackets: 2411573575
      prevTxTooShort: 0
          prevTxTo64: 0
       prevTx65to127: 0
      prevTx128to255: 0
      prevTx256to511: 0
     prevTx512to1023: 0
    prevTx1024to1518: 0
     prevTx1519toMax: 0
       prevTxTooLong: 0
     prevTxBroadcast: 3167189
         prevTxPause: 0
     prevTxMulticast: 0
      prevTxUnderrun: 0
     prevTxCollision: 0
   prevTxExCollision: 0
 prevTxMultCollision: 0
 prevTxSingCollision: 0
    prevTxExDeferred: 0
      prevTxDeferred: 0
 prevTxLateCollision: 0
prevTxTotalCollision: 0
  prevTxPauseHonored: 0
          prevTxDrop: 0
        prevTxJabber: 0
     prevTxFCFSError: 0
       prevTxControl: 0
      prevTxFragment: 0
           last_seen: 2023-01-04 04:30:07
             present: 1
*************************** 2. row ***************************
             host_id: 3
               index: 4
                name: ETHER4
             RxBytes: 1986681419228
           RxPackets: 8106074953
          RxTooShort: 0
              RxTo64: 0
           Rx65to127: 0
          Rx128to255: 0
          Rx256to511: 0
         Rx512to1023: 0
        Rx1024to1518: 0
         Rx1519toMax: 0
           RxTooLong: 0
         RxBroadcast: 5725845
             RxPause: 0
         RxMulticast: 862453
         RxFCFSError: 0
        RxAlignError: 0
          RxFragment: 0
          RxOverflow: 0
           RxControl: 0
         RxUnknownOp: 0
       RxLengthError: 0
         RxCodeError: 0
      RxCarrierError: 0
            RxJabber: 0
              RxDrop: 976936
             TxBytes: 27269348090920
           TxPackets: 22599328040
          TxTooShort: 0
              TxTo64: 0
           Tx65to127: 0
          Tx128to255: 0
          Tx256to511: 0
         Tx512to1023: 0
        Tx1024to1518: 0
         Tx1519toMax: 0
           TxTooLong: 0
         TxBroadcast: 9786720
             TxPause: 0
         TxMulticast: 1071520
          TxUnderrun: 0
         TxCollision: 0
       TxExCollision: 0
     TxMultCollision: 0
     TxSingCollision: 0
        TxExDeferred: 0
          TxDeferred: 0
     TxLateCollision: 0
    TxTotalCollision: 0
      TxPauseHonored: 0
              TxDrop: 0
            TxJabber: 0
         TxFCFSError: 0
           TxControl: 0
          TxFragment: 0
          curRxBytes: 1396064
        curRxPackets: 6565
       curRxTooShort: 0
           curRxTo64: 0
        curRx65to127: 0
       curRx128to255: 0
       curRx256to511: 0
      curRx512to1023: 0
     curRx1024to1518: 0
      curRx1519toMax: 0
        curRxTooLong: 0
      curRxBroadcast: 28
          curRxPause: 0
      curRxMulticast: 4
      curRxFCFSError: 0
     curRxAlignError: 0
       curRxFragment: 0
       curRxOverflow: 0
        curRxControl: 0
      curRxUnknownOp: 0
    curRxLengthError: 0
      curRxCodeError: 0
   curRxCarrierError: 0
         curRxJabber: 0
           curRxDrop: 0
          curTxBytes: 24860212
        curTxPackets: 22656
       curTxTooShort: 0
           curTxTo64: 0
        curTx65to127: 0
       curTx128to255: 0
       curTx256to511: 0
      curTx512to1023: 0
     curTx1024to1518: 0
      curTx1519toMax: 0
        curTxTooLong: 0
      curTxBroadcast: 45
          curTxPause: 0
      curTxMulticast: 5
       curTxUnderrun: 0
      curTxCollision: 0
    curTxExCollision: 0
  curTxMultCollision: 0
  curTxSingCollision: 0
     curTxExDeferred: 0
       curTxDeferred: 0
  curTxLateCollision: 0
 curTxTotalCollision: 0
   curTxPauseHonored: 0
           curTxDrop: 0
         curTxJabber: 0
      curTxFCFSError: 0
        curTxControl: 0
       curTxFragment: 0
         prevRxBytes: 1986681419228
       prevRxPackets: 8106074953
      prevRxTooShort: 0
          prevRxTo64: 0
       prevRx65to127: 0
      prevRx128to255: 0
      prevRx256to511: 0
     prevRx512to1023: 0
    prevRx1024to1518: 0
     prevRx1519toMax: 0
       prevRxTooLong: 0
     prevRxBroadcast: 5725845
         prevRxPause: 0
     prevRxMulticast: 862453
     prevRxFCFSError: 0
    prevRxAlignError: 0
      prevRxFragment: 0
      prevRxOverflow: 0
       prevRxControl: 0
     prevRxUnknownOp: 0
   prevRxLengthError: 0
     prevRxCodeError: 0
  prevRxCarrierError: 0
        prevRxJabber: 0
          prevRxDrop: 976936
         prevTxBytes: 27269348090920
       prevTxPackets: 22599328040
      prevTxTooShort: 0
          prevTxTo64: 0
       prevTx65to127: 0
      prevTx128to255: 0
      prevTx256to511: 0
     prevTx512to1023: 0
    prevTx1024to1518: 0
     prevTx1519toMax: 0
       prevTxTooLong: 0
     prevTxBroadcast: 9786720
         prevTxPause: 0
     prevTxMulticast: 1071520
      prevTxUnderrun: 0
     prevTxCollision: 0
   prevTxExCollision: 0
 prevTxMultCollision: 0
 prevTxSingCollision: 0
    prevTxExDeferred: 0
      prevTxDeferred: 0
 prevTxLateCollision: 0
prevTxTotalCollision: 0
  prevTxPauseHonored: 0
          prevTxDrop: 0
        prevTxJabber: 0
     prevTxFCFSError: 0
       prevTxControl: 0
      prevTxFragment: 0
           last_seen: 2023-01-04 04:30:07
             present: 1
2 rows in set (0.000 sec)

**Comment by coder-binary1** [comment]
and Here is the log output on web-UI

![image](https://user-images.githubusercontent.com/96922458/210452606-147190f1-ba90-45e2-a686-016468f6fc78.png)
![image](https://user-images.githubusercontent.com/96922458/210452672-21e76d45-10e0-49ff-8d7b-5d27933cf6fe.png)

**Comment by coder-binary1** [comment]
@TheWitness I reported this issue, so you can't close it without discussing it with me.

**Comment by skywalker-znz** [comment]
@TheWitness can we please continue on the forum, still cannot get mikrotik poller work. Thank you.
