### ISSUE TITLE
Plugin management goes blank when adding this to /plugins/ folder

### ISSUE THREAD

**Issue by booxdk** [Cacti/plugin_mikrotik#7]
Hi

When extracting, renaming to mikrotik and copying this plugin to the Cacti plugins folder the Cacti Plugin management page goes blank - any ideas ?

BooX

-------------------------------------------------------------------------------------------
Cacti info.:
Date	Tue, 04 Apr 2017 19:51:59 +0200
Cacti Version	0.8.8b
Cacti OS	unix
SNMP Version	NET-SNMP version: 5.7.2.1
RRDTool Version	RRDTool 1.4.x
Hosts	1
Graphs	4
Data Sources	Script/Command: 5
Total: 5
Poller Information
Interval	300
Type	cmd.php
Items	Action[1]: 5
Total: 5
Concurrent Processes	1
Max Threads	1
PHP Servers	1
Script Timeout	25
Max OID	10
Last Run Statistics	Time:0.1072 Method:cmd.php Processes:1 Threads:N/A Hosts:2 HostsPerProcess:2 DataSources:5 RRDsProcessed:5
PHP Information
PHP Version	5.6.30-0+deb8u1
PHP OS	Linux
PHP uname	Linux Cacti 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64
PHP SNMP	Installed
max_execution_time	30
memory_limit	128M

**Comment by cigamit** [comment]
> Cacti Version	0.8.8b
This version of the plugin only works on Cacti 1.X and above.  Your Cacti install is a really old and is not compatible.

**Comment by booxdk** [comment]
Hi - Thank you very much. It seems that 0.8.8b is the newest in the apt-package for Debian. I'll look into how to manually update to 1.1.1.2 and give that a try.
