### ISSUE TITLE
Graphs skipped by Rule, or Not Created

### ISSUE THREAD

**Issue by ThunderBlade333** [Cacti/plugin_mikrotik#70]
![Screenshot (7)](https://user-images.githubusercontent.com/123804072/215257738-c0fdc0e0-f6a2-4424-b6c9-2e00d1ef65f5.png)

How to fix this problem?

**Comment by ThunderBlade333** [comment]
![image](https://user-images.githubusercontent.com/123804072/215278748-3258a3ec-e17a-4b9a-b889-035f50d77076.png)
This is maybe cause by this as I get error during importing packages.

php /opt/cacti/cli/import_package.php --filename=/opt/cacti/plug                                                     ins/mikrotik/templates/MikroTik_Device.xml.gz
Read 171026 bytes of Package data
Import Results Cacti has imported the following items for the Package:Package Fil                                                     es/opt/cacti/scripts/ss_hstats.php [written]/opt/cacti/scripts/ping.pl [written]/                                                     opt/cacti/scripts/ss_mikrotik_snmpget.php [written]/opt/cacti/scripts/ss_count_oi                                                     ds.php [written]/opt/cacti/scripts/ss_mikrotik_cpu.php [written]/opt/cacti/script                                                     s/ss_mikrotik_procs.php [written]/opt/cacti/scripts/ss_mikrotik_mem.php [written]                                                     /opt/cacti/scripts/ss_mikrotik_disk.php [written]/opt/cacti/scripts/ss_mikrotik_u                                                     sers.php [written]/opt/cacti/scripts/ss_mikrotik_uptime.php [written]/opt/cacti/s                                                     cripts/ss_mikrotik_health.php [written]/opt/cacti/scripts/ss_mikrotik_wapcount.ph                                                     p [written]/opt/cacti/scripts/ss_mikrotik_wrcount.php [written]/opt/cacti/scripts                                                     /ss_mikrotik_trees.php [written]/opt/cacti/scripts/ss_mikrotik_qcount.php [writte                                                     n]/opt/cacti/plugins/mikrotik/templates/resource/script_server/mikrotik_wireless_                                                     reg.xml [not writable]/opt/cacti/plugins/mikrotik/templates/resource/script_serve                                                     r/mikrotik_queues.xml [not writable]/opt/cacti/plugins/mikrotik/templates/resourc                                                     e/script_server/mikrotik_trees.xml [not writable]/opt/cacti/plugins/mikrotik/temp                                                     lates/resource/script_server/mikrotik_qusers.xml [not writable]/opt/cacti/plugins                                                     /mikrotik/templates/resource/script_server/mikrotik_interfaces.xml [not writable]                                                     /opt/cacti/scripts/ss_mikrotik_wireless_reg.php [written]/opt/cacti/scripts/ss_mi                                                     krotik_queues.php [written]/opt/cacti/scripts/ss_mikrotik_qtrees.php [written]/op                                                     t/cacti/scripts/ss_mikrotik_qusers.php [written]/opt/cacti/scripts/ss_mikrotik_in                                                     terfaces.php [written]CDEF[success] Turn Uptime to Days [unchanged][success] Turn                                                      Bytes into Bits [unchanged][success] Turn Seconds into Hours [new][success] Make                                                      Per 5 Minutes [unchanged]GPRINT Preset[success] Normal [unchanged][success] Exac                                                     t Numbers [unchanged][success] Percentage as Decimal [unchanged]Data Input Method                                                     [success] Device - Polling Time [unchanged][success] Device - Uptime [unchanged][                                                     success] Unix - Ping Host [unchanged][success] MikroTik - Device - SNMP Get [new]                                                     [success] MikroTik - Device - Count Oids [new][success] MikroTik - Device - CPU U                                                     tilization [new][success] MikroTik - Device - Processes [new][success] MikroTik -                                                      Device - Memory Utilization [new][success] MikroTik - Device - Disk Utilization                                                      [new][success] MikroTik - Device - Users [new][success] MikroTik - Device - Uptim                                                     e [new][success] MikroTik - Device - Health [new][success] MikroTik - Device - Wi                                                     reless APs [new][success] MikroTik - Device - Wireless Reg [new][success] MikroTi                                                     k - Device - Trees [new][success] MikroTik - Device - Queues [new][success] Get S                                                     cript Server Data (Indexed) [unchanged]Data Template[success] Device - Polling Ti                                                     me [unchanged][success] Device - Uptime [unchanged][success] Unix - Ping Host [un                                                     changed][success] MikroTik - Device - PPP Active [new][success] MikroTik - Device                                                      - IP Routes [new][success] MikroTik - Device - Wireless Connections [new][succes                                                     s] MikroTik - Device - IP/ARP Entries [new][success] MikroTik - Device - CPU Util                                                     ization [new][success] MikroTik - Device - Processes [new][success] MikroTik - De                                                     vice - Memory Utilization [new][success] MikroTik - Device - Disk Utilization [ne                                                     w][success] MikroTik - Device - Users [new][success] MikroTik - Device - Uptime [                                                     new][success] MikroTik - Device - Health - 12.0 Voltage [new][success] MikroTik -                                                      Device - Health - 5.0 Voltage [new][success] MikroTik - Device - Health - 3.3 Vo                                                     ltage [new][success] MikroTik - Device - Health - Core Voltage [new][success] Mik                                                     roTik - Device - Health - Voltage [new][success] MikroTik - Device - Health - CPU                                                      Temperature [new][success] MikroTik - Device - Health - Processor Temperature [n                                                     ew][success] MikroTik - Device - Health - Sensor Temperature [new][success] Mikro                                                     Tik - Device - Health - Temperature [new][success] MikroTik - Device - Health - P                                                     ower [new][success] MikroTik - Device - Health - Current [new][success] MikroTik                                                      - Device - Wireless APs [new][success] MikroTik - Device - Wireless Reg [new][suc                                                     cess] MikroTik - Device - Trees [new][success] MikroTik - Device - Queues [new][s                                                     uccess] MikroTik - DHCP - Leases [new][success] MikroTik - Wireless Reg - Data Ra                                                     tes [new][success] MikroTik - Wireless Reg - Packets [new][success] MikroTik - Wi                                                     reless Reg - Traffic [new][success] MikroTik - Wireless Reg - Uptime [new][succes                                                     s] MikroTik - Queue - Packets [new][success] MikroTik - Queue - Traffic [new][suc                                                     cess] MikroTik - Queue - Queues/Drops [new][success] MikroTik - Trees - Packets [                                                     new][success] MikroTik - Trees - Bytes [new][success] MikroTik - Users - Total Pa                                                     ckets In/Out [new][success] MikroTik - Users - Current Packets In/Out [new][succe                                                     ss] MikroTik - Users - Total Bytes In/Out [new][success] MikroTik - Users - Curre                                                     nt Bytes In/Out [new][success] MikroTik - Users - Connect Time [new][success] Mik                                                     roTik - Interfaces - Bytes Tx/Rx [new][success] MikroTik - Interfaces - Packets T                                                     x/Rx [new][success] MikroTik - Interfaces - Rx Distribution [new][success] MikroT                                                     ik - Interfaces - Special Tx/Rx [new][success] MikroTik - Interfaces - Tx Distrib                                                     ution [new][success] MikroTik - Interfaces - Tx Errors [new][success] MikroTik -                                                      Interfaces - Rx Errors [new]Graph Template[success] Device - Polling Time [unchan                                                     ged][success] Device - Uptime [unchanged][success] Unix - Ping Latency [unchanged                                                     ][success] MikroTik - Device - PPP Active [new][success] MikroTik - Device - IP R                                                     outes [new][success] MikroTik - Device - Wireless Connections [new][success] Mikr                                                     oTik - Device - IP/ARP Entries [new][success] MikroTik - Device - CPU Utilization                                                      [new][success] MikroTik - Device - Processes [new][success] MikroTik - Device -                                                      Memory Utilization [new][success] MikroTik - Device - Disk Utilization [new][succ                                                     ess] MikroTik - Device - Users [new][success] MikroTik - Device - Uptime [new][su                                                     ccess] MikroTik - Device - Health - 12.0 Voltage [new][success] MikroTik - Device                                                      - Health - 5.0 Voltage [new][success] MikroTik - Device - Health - 3.3 Voltage [                                                     new][success] MikroTik - Device - Health - Core Voltage [new][success] MikroTik -                                                      Device - Health - Voltage [new][success] MikroTik - Device - Health - CPU Temper                                                     ature [new][success] MikroTik - Device - Health - Processor Temperature [new][suc                                                     cess] MikroTik - Device - Health - Sensor Temperature [new][success] MikroTik - D                                                     evice - Health - Temperature [new][success] MikroTik - Device - Health - Power [n                                                     ew][success] MikroTik - Device - Health - Current [new][success] MikroTik - Devic                                                     e - Wireless APs [new][success] MikroTik - Device - Wireless Regs [new][success]                                                      MikroTik - Device - Trees [new][success] MikroTik - Device - Queues [new][success                                                     ] MikroTik - DHCP - Leases [new][success] MikroTik - Wireless Reg - Data Rates [n                                                     ew][success] MikroTik - Wireless Reg - Packets [new][success] MikroTik - Wireless                                                      Reg - Traffic (bytes/sec) [new][success] MikroTik - Wireless Reg - Traffic (bits                                                     /sec) [new][success] MikroTik - Wireless Reg - Uptime [new][success] MikroTik - Q                                                     ueues - Packets In/Out [new][success] MikroTik - Queues - Traffic (bytes/sec) [ne                                                     w][success] MikroTik - Queues - Traffic (bits/sec) [new][success] MikroTik - Queu                                                     es - Drops [new][success] MikroTik - Queues - Queues In/Out [new][success] MikroT                                                     ik - Trees - Packets Total [new][success] MikroTik - Trees - Traffic (bits/sec) [                                                     new][success] MikroTik - Users - Total Packets In/Out [new][success] MikroTik - U                                                     sers - Current Packets In/Out [new][success] MikroTik - Users - Total Bytes In/Ou                                                     t [new][success] MikroTik - Users - Current Bytes In/Out [new][success] MikroTik                                                      - Users - Connect Time [new][success] MikroTik - Interfaces - Bytes Tx/Rx [new][s                                                     uccess] MikroTik - Interfaces - Packets Tx/Rx [new][success] MikroTik - Interface                                                     s - Rx Distribution [new][success] MikroTik - Interfaces - Special Tx/Rx [new][su                                                     ccess] MikroTik - Interfaces - Tx Distribution [new][success] MikroTik - Interfac                                                     es - Tx Errors [new][success] MikroTik - Interfaces - Rx Errors [new]Data Query[s                                                     uccess] MikroTik - Wireless Reg [new][success] MikroTik - Queues [new][success] M                                                     ikroTik - Trees [new][success] MikroTik - Users [new][success] MikroTik - Interfa                                                     ces [new]Device Template[success] MikroTik Device [new]

**Comment by TheWitness** [comment]
So, I'm working on getting 1.2.24 and a large swath of plugins ready.  I'll do a QA pass tomorrow just to make sure everything is fine.

**Comment by TheWitness** [comment]
I think I see the problem.

**Comment by TheWitness** [comment]
Okay, if you upgrade to 1.2.24, the new Device Package should work on everything.  I've just tagged version 3.1

**Comment by ThunderBlade333** [comment]
Okay boss

**Comment by ThunderBlade333** [comment]
Problem Solved. Thank you boss.
