### ISSUE TITLE
v2.4 does not get interfaces..

### ISSUE THREAD

**Issue by PAOK1926** [Cacti/plugin_mikrotik#75]
I'm using cacti 1.2.16 with 2.4 version of your plugin.
when i add a mikrotik device, it does not get the interfaces..

**Comment by PAOK1926** [comment]
updated to latest cacti, your latest script, but still no interfaces.
this is the debug of the query:

`<div id="dqdebug" class="cactiTable">
				<div id="clipboardHeader88b1e91dcfb3c99aa17c2dc121c308ee">
					<div class="cactiTableTitle">
						<span style="padding:3px;">Data Query Debug Information</span>
					</div>
					<div class="cactiTableButton">
						<span>
							<a class="linkCopyDark cactiTableCopy fa fa-copy" id="copyToClipboard88b1e91dcfb3c99aa17c2dc121c308ee" title="" aria-describedby="ui-id-14"></a>
							<a id="dbghide" class="fa fa-times fa-trash-alt" href="https://10.107.1.25/cacti/host.php?header=true&amp;action=edit&amp;id=5&amp;display_dq_details=true#" title="Hide"></a>
						</span>
					</div>
					

Total: 0.000000,  Delta: 0.000000, Found data query XML file at  '/usr/share/cacti/site/resource/script_server/mikrotik_interfaces.xml' Total: 0.000000, Delta: 0.000000, Running Data Query [11]. Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query]. Total: 0.000000, Delta: 0.000000, XML file parsed ok. Total: 0.100000, Delta: 0.100000, Data Query returned no indexes. Total: 0.100000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported Total: 0.100000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /usr/share/cacti/site/scripts/ss_mikrotik_interfaces.php '5'  'num_indexes'' Total: 0.180000, Delta: 0.080000, ERROR: Data Query returned no indexes. | Total: 0.000000,  Delta: 0.000000, Found data query XML file at  '/usr/share/cacti/site/resource/script_server/mikrotik_interfaces.xml' | Total: 0.000000, Delta: 0.000000, Running Data Query [11]. | Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query]. | Total: 0.000000, Delta: 0.000000, XML file parsed ok. | Total: 0.100000, Delta: 0.100000, Data Query returned no indexes. | Total: 0.100000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported | Total: 0.100000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /usr/share/cacti/site/scripts/ss_mikrotik_interfaces.php '5'  'num_indexes'' | Total: 0.180000, Delta: 0.080000, ERROR: Data Query returned no indexes.
-- | -- | -- | -- | -- | -- | -- | -- | --
Total: 0.000000,  Delta: 0.000000, Found data query XML file at  '/usr/share/cacti/site/resource/script_server/mikrotik_interfaces.xml'
Total: 0.000000, Delta: 0.000000, Running Data Query [11].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.100000, Delta: 0.100000, Data Query returned no indexes.
Total: 0.100000, Delta: 0.000000, <arg_num_indexes> exists  in XML file but no data returned., 'Index Count Changed' not supported
Total: 0.100000, Delta: 0.000000, Executing script for num of  indexes '"/usr/bin/php" -q  /usr/share/cacti/site/scripts/ss_mikrotik_interfaces.php '5'  'num_indexes''
Total: 0.180000, Delta: 0.080000, ERROR: Data Query returned no indexes.


				</div>
			</div>`

**Comment by sadm2014** [comment]
Confirm this bug, have similar result:

<div id="dqdebug" class="cactiTable" style="display: table; width: 1557.91px; border-width: 0px; border-color: rgb(0, 67, 140); border-style: solid; margin-left: auto; margin-right: auto; color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="clipboardHeader30c596c563fce59e7e22aff50a29ec2d" style="display: block;">

Total: 0.000000, Delta: 0.000000, Found data query XML file at '/usr/share/cacti/site/resource/script_server/mikrotik_interfaces.xml'Total: 0.000000, Delta: 0.000000, Running Data Query [18].Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query].Total: 0.000000, Delta: 0.000000, XML file parsed ok.Total: 0.180000, Delta: 0.170000, Data Query returned no indexes.Total: 0.180000, Delta: 0.000000, <arg_num_indexes> exists in XML file but no data returned., 'Index Count Changed' not supportedTotal: 0.180000, Delta: 0.000000, Executing script for num of indexes '"/usr/bin/php" -q /usr/share/cacti/site/scripts/ss_mikrotik_interfaces.php '52' 'num_indexes''Total: 0.330000, Delta: 0.150000, ERROR: Data Query returned no indexes. | Total: 0.000000, Delta: 0.000000, Found data query XML file at '/usr/share/cacti/site/resource/script_server/mikrotik_interfaces.xml' | Total: 0.000000, Delta: 0.000000, Running Data Query [18]. | Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query]. | Total: 0.000000, Delta: 0.000000, XML file parsed ok. | Total: 0.180000, Delta: 0.170000, Data Query returned no indexes. | Total: 0.180000, Delta: 0.000000, <arg_num_indexes> exists in XML file but no data returned., 'Index Count Changed' not supported | Total: 0.180000, Delta: 0.000000, Executing script for num of indexes '"/usr/bin/php" -q /usr/share/cacti/site/scripts/ss_mikrotik_interfaces.php '52' 'num_indexes'' | Total: 0.330000, Delta: 0.150000, ERROR: Data Query returned no indexes.
-- | -- | -- | -- | -- | -- | -- | -- | --
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/usr/share/cacti/site/resource/script_server/mikrotik_interfaces.xml'
Total: 0.000000, Delta: 0.000000, Running Data Query [18].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.180000, Delta: 0.170000, Data Query returned no indexes.
Total: 0.180000, Delta: 0.000000, <arg_num_indexes> exists in XML file but no data returned., 'Index Count Changed' not supported
Total: 0.180000, Delta: 0.000000, Executing script for num of indexes '"/usr/bin/php" -q /usr/share/cacti/site/scripts/ss_mikrotik_interfaces.php '52' 'num_indexes''
Total: 0.330000, Delta: 0.150000, ERROR: Data Query returned no indexes.

</div></div><div id="host_edit3" class="cactiTable" style="display: table; width: 1557.91px; border-width: 0px; border-color: rgb(0, 67, 140); border-style: solid; margin-left: auto; margin-right: auto; color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: center;"><div style="display: block;"><div class="cactiTableTitle" style="display: block; color: white; float: left; line-height: 25px; height: 25px; text-align: left; width: 1090.53px; background-color: rgb(0, 67, 140); font-size: 12px; user-select: none;"><span style="color: white; padding: 0px; line-height: 25px; white-space: nowrap; overflow: hidden; background: transparent; user-select: none;">Associated Data Queries</span></div><div class="cactiTableButton" style="display: block; float: right; line-height: 25px; height: 25px; text-align: right; width: 467.372px; background-color: rgb(0, 67, 140); white-space: nowrap; user-select: none;"><span style="color: white; padding: 0px; line-height: 25px; white-space: nowrap; overflow: hidden; background: transparent; user-select: none;"></span></div></div></div><br class="Apple-interchange-newline">

**Comment by TheWitness** [comment]
I've done a lot to clean things up, but I think it requires like 1.2.23+ to work well.  You also need to re-import the packages.

**Comment by sadm2014** [comment]
I have 1.2.24, re-imported packages but have no success

**Comment by TheWitness** [comment]
Did you import the packages or the old template?

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/plugin_mikrotik/assets/1439914/0287d548-ba49-4aa8-a7fe-70922331565f)
