### ISSUE TITLE
SQL Syntax Error in poller_mikrotik.php

### ISSUE THREAD

**Issue by jaysenjohnson** [Cacti/plugin_mikrotik#78]
I am running a new, fresh install of Cacti 1.2.26 on Ubuntu 22.04 LTS. Mariadb version 10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.0.  PHP version 8.1.2-1ubuntu2.14 (cli).

We have many sites with MikroTik devices that we are trying to monitor.  I installed the latest plugin_mikrotik version 3.1 and I have noticed the following errors in my cacti log files.  Is there a fix for this?  

`2024-01-12 10:40:37 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '^T-$) AND present = 0 AND host_id = '2' AND last_seen < FROM_UNIXTIME(UNIX_TI...' at line 1`

`2024-01-12 10:40:37 - CMDPHP SQL Backtrace:  (/plugins/mikrotik/poller_mikrotik.php[137]:checkHost(), /plugins/mikrotik/poller_mikrotik.php[788]:db_execute_prepared())`

Thanks in advance for the help.

Jaysen

**Comment by TheWitness** [comment]
I've fixed this.  Please test with the latest poller_mikrotik.php.

**Comment by jaysenjohnson** [comment]
Thank you very much!  I plan to do more testing in about a week once I am done with another project I've been tasked on.  I'll let you know my results.  I appreciate the help on this.

Jaysen
