### ISSUE TITLE
Warning:  "Error: OID not increasing: .1.3.6.1.2.1.1.1.0"

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_mikrotik#8]
Cacti have this warning:
`2017-04-21 22:50:14 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mikrotik/poller_mikrotik.php: 138 checkHost)(/plugins/mikrotik/poller_mikrotik.php: 768 collect_system)(/plugins/mikrotik/poller_mikrotik.php: 824 cacti_snmp_walk)(/plugins/mikrotik/snmp.php: 339 snmp2_real_walk)(CactiErrorHandler)(/lib/functions.php: 4264 cacti_debug_backtrace)`

**Comment by cigamit** [comment]
Well that's odd.  Is the device reponding to snmp walks of the system mib?

**Comment by pautiina** [comment]
Hello.
I have try get debug message but after change log level this message away, and I cannot give you more information.
I have Mikrotik and many other type devices. All devices reponding to snmp walks of the system mib.
Let the request be opened. If the message does not go any farther, I'll close it.

**Comment by cigamit** [comment]
My guess is that the device was not fully up, or did not respond.  You may be able to emulate it that way.

**Comment by pautiina** [comment]
This message repeat again, but I cannot found what is the device. Some device is down.
I have 12 down hosts but message repeat 19 count for one poller running.

**Comment by pautiina** [comment]
This issues also #15

**Comment by cigamit** [comment]
Update to latest tik.
