### ISSUE TITLE
file not found: ss_mikrotik_wireless_reg.php

### ISSUE THREAD

**Issue by maximt** [Cacti/plugin_mikrotik#9]
data query output for 'index'
Found index: Could not open input file: cacti/plugins/mikrotik/templates/scripts/ss_mikrotik_wireless_reg.php

ls -1 cacti/plugins/mikrotik/templates/scripts
index.php
ss_count_oids.php
ss_mikrotik_cpu.php
ss_mikrotik_disk.php
ss_mikrotik_health.php
ss_mikrotik_interfaces.php
ss_mikrotik_mem.php
ss_mikrotik_procs.php
ss_mikrotik_qcount.php
ss_mikrotik_qtrees.php
ss_mikrotik_queue_simple.php
ss_mikrotik_queues.php
ss_mikrotik_qusers.php
ss_mikrotik_snmpget.php
ss_mikrotik_trees.php
ss_mikrotik_uptime.php
ss_mikrotik_users.php
ss_mikrotik_wapcount.php
ss_mikrotik_wrcount.php

https://github.com/Cacti/plugin_mikrotik/tree/master/templates/scripts - no ss_mikrotik_wireless_reg.php too

**Comment by cigamit** [comment]
This is resolved in version 2.1.  Make sure you re-import the device package.
